
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[476] =
    {   0,
      103,  103,  106,  106,  109,  107,  108,   99,  107,  108,
      100,  108,   98,  107,  108,   42,  107,  108,  107,  108,
       55,  107,  108,   45,  107,  108,  107,  108,   64,  107,
      108,   65,  107,  108,16445,   44,  107,  108,   40,  107,
      108,   73,  107,  108,   41,  107,  108,   72,   81,  107,
      108,16458,   56,  107,  108,   84,  107,  108,16461,   84,
      107,  108,16461,   71,  107,  108,   70,  107,  108,   54,
      107,  108,   60,  107,  108,   53,  107,  108,   97,  107,
      108,16480,   68,  107,  108,   69,  107,  108,16447,   43,
      107,  108,  107,  108,   97,  107,  108,16480,   97,  107,

      108,16480,   97,  107,  108,16480,   97,  107,  108,16480,
       97,  107,  108,16480,   97,  107,  108,16480,   97,  107,
      108,16480,   97,  107,  108,16480,   97,  107,  108,16480,
       97,  107,  108,16480,   97,  107,  108,16480,   97,  107,
      108,16480,   97,  107,  108,16480,   97,  107,  108,16480,
       66,  107,  108,   46,  107,  108,   67,  107,  108,16446,
      103,  108,  102,  108,  106,  108,  108,  108,    1,  108,
       50,   95,16475,   60,   48,   38, 8253,   36,16418,   37,
    16419, 8266,   81,16458,  104,  101, 8269,   81,16458,   84,
    16461,   59,   57,   51,   49,   52,   58, 8288,   97,16480,

     8255,   94,16474,   97,16480,   97,16480,   97,16480,   97,
    16480,   97,16480,   97,16480,   97,16480,   97,16480,   97,
    16480,   20,   97,16480,   97,16480,   97,16480,   97,16480,
       97,16480,   97,16480,   97,16480,   97,16480,   97,16480,
       97,16480,   97,16480,   97,16480,   97,16480,   47, 8254,
      103,  106,  105, 8283,   95,16475,   92,16472, 8226, 8227,
       39,   81,16458,   87,16464,   82,   83,16459,16460,   86,
    16463,   85,16462, 8282,   97,16480,   97,16480,   97,16480,
       97,16480,   97,16480,   97,16480,   21,   97,16480,   97,
    16480,   97,16480,   97,16480,   97,16480,   29,   97,16480,

       27,   97,16480,   11,   97,16388,16480,   97,16480,   97,
    16480,   97,16480,   97,16480,   97,16480,   97,16480,   97,
    16480,   24,   97,16480, 8283, 8280,   83,16460,   82,16459,
     8272, 8267, 8268, 8271, 8270,   97,16480,   26,   97,16480,
       97,16480,   97,16480,   97,16480,   18,   97,16480,   97,
    16480,   97,16480,   16,   97,16480,   32,   97,16480,   97,
    16480,   31,   97,16480, 8196, 8288,   97,16480,   97,16480,
       97,16480,   97,16480,   97,16480,    9,   97,16386,16480,
       33,   97,16480,   93,16473, 8268, 8267,   12,   97,16389,
    16480,   28,   97,16480,   97,16480,   97,16480,   97,16480,

       10,   97,16387,16480,   97,16480,   97,16480,   22,   97,
    16480,   97,16480,   97,16480,   97,16480, 8194, 8288, 8281,
     8197, 8288,   97,16480,   97,16480,   97,16480, 8195, 8288,
       23,   97,16480,   97,16480,   15,   97,16392,16480,   17,
       97,16480,   25,   97,16480,   97,16480,   30,   97,16480,
       97,16480,   19,   97,16480, 8200, 8288,   13,   97,16390,
    16480,   97,16480, 8198, 8288,   97,16480,   97,16480,   14,
       97,16391,16480, 8199, 8288
    } ;

static const flex_int16_t yy_accept[281] =
    {   0,
        1,    1,    1,    2,    3,    4,    5,    5,    5,    6,
        8,   11,   13,   16,   19,   21,   24,   27,   29,   32,
       36,   39,   42,   45,   48,   53,   56,   60,   64,   67,
       70,   73,   76,   79,   83,   86,   90,   93,   95,   99,
      103,  107,  111,  115,  119,  123,  127,  131,  135,  139,
      143,  147,  151,  154,  157,  161,  163,  165,  167,  168,
      169,  171,  172,  172,  174,  174,  175,  176,  177,  177,
      177,  178,  178,  180,  182,  183,  183,  183,  185,  186,
      187,  188,  188,  190,  192,  192,  192,  192,  192,  193,
      194,  195,  196,  197,  198,  199,  199,  201,  202,  202,

      202,  202,  204,  206,  208,  210,  212,  214,  216,  218,
      220,  222,  225,  227,  229,  231,  233,  235,  237,  239,
      241,  243,  245,  247,  249,  250,  251,  251,  252,  253,
      254,  255,  255,  257,  257,  257,  257,  257,  257,  257,
      259,  259,  260,  260,  261,  261,  262,  262,  264,  264,
      266,  266,  270,  272,  274,  275,  275,  277,  279,  281,
      283,  285,  287,  290,  292,  294,  296,  298,  301,  304,
      308,  310,  312,  314,  316,  318,  320,  322,  325,  326,
      326,  326,  326,  326,  326,  327,  327,  327,  327,  329,
      329,  331,  332,  332,  334,  334,  335,  335,  336,  336,

      338,  341,  343,  345,  347,  350,  352,  354,  357,  360,
      362,  365,  367,  367,  369,  371,  373,  375,  377,  381,
      384,  384,  384,  384,  386,  387,  387,  388,  388,  392,
      395,  397,  399,  401,  405,  407,  409,  412,  414,  416,
      418,  420,  420,  420,  420,  421,  421,  423,  423,  425,
      427,  429,  431,  431,  434,  436,  440,  443,  446,  446,
      446,  448,  451,  453,  456,  458,  458,  458,  462,  464,
      464,  466,  466,  468,  468,  470,  474,  476,  476,  476
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   28,   27,   27,   29,   27,
       30,   30,   30,   30,   30,   30,   30,   30,   31,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,   38,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   30,   48,   49,   50,   51,
       52,   53,   30,   54,   55,   56,   57,   58,   59,   60,
       61,   30,   62,   63,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    4,    1,
        1,    5,    1,    1,    1,    1,    1,    6,    6,    6,
        6,    1,    1,    1,    1,    1,    6,    6,    6,    3,
        3,    3,    3,    1,    1,    1,    1,    1,    6,    6,
        6,    6,    6,    6,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[290] =
    {   0,
        0,    0,  302,  293,  279,  277,  277,  261,  259,  973,
      973,  973,  973,  230,   59,  206,   58,  159,  973,   64,
      167,   56,  973,   55,   68,   65,   93,   99,  153,  973,
       49,  149,   50,   75,  973,   88,  141,   96,   97,  102,
      104,  126,  128,  134,  140,  152,  136,  154,  156,  145,
      158,  161,  973,   60,  165,    0,  973,    0,  135,  973,
      973,  973,   92,  167,  214,  973,  973,  125,  137,  100,
      973,  169,  173,  178,  973,  184,  109,  207,  973,  973,
      973,  193,  257,  263,  184,  222,  187,    0,  973,   91,
      973,  973,  973,   85,  973,  205,  210,  973,  212,  160,

      186,  214,  226,  218,  244,  241,  235,  248,  253,  259,
      284,  290,  295,  298,  300,  305,  308,  310,  312,  315,
      317,  319,  321,  323,  973,  973,  325,    0,    0,  973,
      973,  327,  330,  331,  337,  372,    0,  399,  426,  335,
      465,  973,  338,  973,  341,  973,  366,  430,  443,  379,
      384,  472,  405,  349,  973,  359,  367,  392,  426,  418,
      474,  476,  385,  481,  483,  485,  491,  428,  433,  493,
      495,  499,  503,  507,  509,  511,  523,  525,  466,  535,
      527,  553,  580,  607,  973,  545,   95,  532,  565,  537,
      584,  973,  572,  973,  574,  973,  586,  973,  607,  609,

      611,  613,  626,  628,  634,  636,  638,  640,  649,  651,
      655,  973,  657,  659,  661,  663,  667,  671,  673,  675,
      524,  700,  727,  679,  973,  683,  973,  685,  687,  690,
      698,  703,  692,  696,  706,  712,  710,  721,  719,  727,
      973,  729,  758,  785,  973,  731,  973,  733,  760,  755,
      777,  973,  747,  757,  779,  785,  787,  789,  814,  526,
      804,  791,  812,  806,  973,  815,  847,  817,  835,  875,
      973,  833,  856,    0,  859,  841,  973,  845,  973,  919,
      925,  931,  937,  943,  948,  954,  960,  966,   87
    } ;

static const flex_int16_t yy_def[290] =
    {   0,
      279,    1,  280,  280,  281,  281,  282,  282,  279,  279,
      279,  279,  279,  279,  283,  279,  279,  284,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  285,  279,  279,  279,  286,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  279,  279,  279,  287,  279,  288,  279,  279,
      279,  279,  283,  279,  283,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  289,  279,  279,
      279,  279,  279,  279,  279,  279,  285,  279,  279,  286,

      286,  279,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  279,  279,  279,  287,  288,  279,
      279,  279,  283,  283,  283,  283,   65,  136,  136,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  289,  279,  279,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  283,  283,
      283,  136,  136,  136,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  279,  279,  285,  285,  285,  285,  285,  285,  285,
      283,  136,  136,  279,  279,  279,  279,  279,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      279,  279,  136,  136,  279,  279,  279,  279,  285,  285,
      285,  279,  279,  285,  285,  285,  285,  285,  136,  283,
      285,  285,  285,  285,  279,  279,  136,  285,  285,  136,
      279,  279,  285,  244,  285,  285,  279,  279,    0,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279
    } ;

static const flex_int16_t yy_nxt[1038] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   28,
       28,   29,   30,   31,   32,   33,   34,   34,   34,   34,
       34,   34,   34,   35,   10,   36,   37,   38,   34,   39,
       40,   41,   42,   43,   44,   34,   45,   34,   34,   46,
       47,   34,   48,   49,   50,   51,   34,   52,   34,   34,
       34,   53,   54,   55,   64,   67,   71,   72,   73,   74,
       75,   76,   90,   91,   93,   94,   79,   95,   96,   66,
       66,   80,   66,   77,   66,   78,   78,   78,   78,   66,
       98,   99,  154,   65,   68,   81,   82,   64,  101,   95,

       96,   81,   82,  224,   95,   96,   95,   96,   83,   66,
       84,   84,   84,   84,   83,   66,   84,   84,   84,   84,
       85,   86,  125,   87,  146,   88,   65,   86,   95,   96,
       95,   96,   85,  102,  141,   86,   95,   96,   95,   96,
      104,   86,   95,   96,   87,  140,  106,   95,   96,   66,
      103,  130,   88,  105,   95,   96,   95,   96,   95,   96,
       95,   96,  101,   95,   96,   66,  108,  126,  127,  131,
      132,   71,   72,   92,  107,  142,  143,   89,  115,  109,
      144,  145,  116,  112,  110,  111,   75,   76,  101,  113,
      114,   66,  117,   70,  118,   81,   82,  102,  119,  124,

      120,  150,  150,  121,  153,  153,  153,   95,   96,   75,
       76,  122,   95,   96,   98,   99,  155,  156,  123,  133,
       95,   96,  134,  102,   78,   78,   78,   78,   95,   96,
       66,  135,  135,  135,  151,  147,  151,   95,   96,  152,
      152,  152,  152,   95,   96,  136,   95,   96,  137,  147,
       95,   96,  134,  134,   62,   95,   96,  134,  279,   75,
       76,   95,   96,   61,  134,   81,   82,  134,  157,  134,
      138,  134,  158,  139,  148,  148,  148,  148,   83,   61,
       84,   84,   84,   84,  160,  149,   95,   96,   59,  161,
       59,   86,   95,   96,  159,   57,  162,   95,   96,  149,

       95,   96,   95,   96,   57,   86,  163,   95,   96,  164,
       95,   96,   95,   96,   95,   96,  279,   95,   96,   95,
       96,   95,   96,   95,   96,   95,   96,  126,  127,  131,
      132,  279,  179,  180,  279,   64,   64,  185,  186,  165,
      142,  143,   64,  144,  145,  167,  279,  166,  171,  279,
      168,  198,  199,  170,  181,  181,  181,  279,  169,  279,
      172,  155,  156,  175,   65,   65,  279,  173,  174,   95,
       96,   65,  279,  177,  279,  176,  178,   64,  188,  279,
      188,  192,  193,  189,  189,  189,  189,   95,   96,  182,
      182,  182,  182,  279,   95,   96,  150,  150,  182,  182,

      182,  152,  152,  152,  152,  200,   65,  196,  197,  279,
      182,  182,  182,  182,  182,  182,  183,  183,  183,  183,
       95,   96,  153,  153,  153,  183,  183,  183,   95,   96,
       95,   96,   75,   76,  201,   95,   96,  183,  183,  183,
      183,  183,  183,  184,  184,  184,  184,  148,  148,  148,
      148,  279,  184,  184,  184,  190,  204,  190,   86,  279,
      191,  191,  191,  191,  184,  184,  184,  184,  184,  184,
      187,   64,   86,  187,  194,  195,   95,   96,   95,   96,
      202,  203,  279,   95,   96,   95,   96,   95,   96,  152,
      152,  152,  152,   95,   96,  212,  213,   95,   96,  187,

       65,   95,   96,  187,  187,   95,   96,  279,  187,   95,
       96,   95,   96,   95,   96,  187,  205,  279,  187,  279,
      187,  208,  187,  279,  206,   95,   96,   95,   96,   64,
      207,   64,   64,  211,  209,  279,  210,  179,  180,  279,
       64,  279,  214,  215,  221,  221,  221,  185,  186,  189,
      189,  189,  189,  219,  191,  191,  191,  191,   65,  216,
       65,   65,  279,  217,  218,  220,  279,  225,  226,   65,
      222,  222,  222,  222,  192,  193,  194,  195,  279,  222,
      222,  222,  189,  189,  189,  189,  227,  228,  196,  197,
      279,  222,  222,  222,  222,  222,  222,  223,  223,  223,

      223,  191,  191,  191,  191,  279,  223,  223,  223,  198,
      199,   95,   96,   95,   96,   95,   96,  279,  223,  223,
      223,  223,  223,  223,  221,  221,  221,  221,   95,   96,
       95,   96,  279,  221,  221,  221,   95,   96,   95,   96,
       95,   96,   95,   96,  279,  221,  221,  221,  221,  221,
      221,   95,   96,   95,   96,  279,  229,   95,   96,  212,
      213,   95,   96,   95,   96,   95,   96,  279,  230,   95,
       96,  279,  231,   95,   96,  241,  242,   95,   96,  279,
      234,  245,  246,  279,  232,  225,  226,  227,  228,  247,
      248,  233,   95,   96,   95,   96,  279,  236,  252,  253,

       95,   96,  279,  237,  235,   95,   96,  239,   95,   96,
      279,  240,   95,   96,   95,   96,  238,  243,  243,  243,
      243,   95,   96,   95,   96,  279,  243,  243,  243,   95,
       96,  241,  242,  245,  246,  247,  248,  251,  243,  243,
      243,  243,  243,  243,  244,  244,  244,  244,  249,  252,
      253,  250,  279,  244,  244,  244,  255,   95,   96,   95,
       96,  254,   95,   96,  279,  244,  244,  244,  244,  244,
      244,  256,  258,  279,  257,  259,  259,  259,  259,   95,
       96,   95,   96,  279,  259,  259,  259,  265,  266,   95,
       96,   95,   96,   95,   96,  279,  259,  259,  259,  259,

      259,  259,  260,  260,  260,  260,   95,   96,   95,   96,
      262,  260,  260,  260,   95,   96,  261,  265,  266,  271,
      272,  264,  279,  260,  260,  260,  260,  260,  260,  279,
      263,  267,  267,  267,  267,  271,  272,   95,   96,  279,
      267,  267,  267,  277,  278,  279,  268,  277,  278,  279,
      279,  279,  267,  267,  267,  267,  267,  267,   95,   96,
      279,   95,   96,  269,  270,  270,  270,  270,  279,  279,
      279,  279,  279,  270,  270,  270,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  270,  270,  270,  270,  270,
      270,  273,  274,  274,  274,  274,  279,  279,  279,  279,

      275,  274,  274,  274,  276,  279,  279,  279,  279,  279,
      279,  279,  279,  274,  274,  274,  274,  274,  274,   56,
       56,   56,   56,   56,   56,   58,   58,   58,   58,   58,
       58,   60,   60,   60,   60,   60,   60,   63,   63,   63,
       63,   63,   63,   69,   69,   69,  279,   69,   69,   97,
       97,  279,  279,   97,  100,  100,  100,  100,  100,  100,
      128,  279,  128,  128,  128,  128,  129,  129,  129,  129,
      279,  129,    9,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279
    } ;

static const flex_int16_t yy_chk[1038] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   15,   17,   20,   20,   22,   24,
       25,   25,   31,   31,   33,   33,   26,   34,   34,   24,
       22,   26,   17,   25,   54,   25,   25,   25,   25,   26,
       36,   36,  289,   15,   17,   27,   27,   63,   38,   39,

       39,   28,   28,  187,   40,   40,   41,   41,   27,   94,
       27,   27,   27,   27,   28,   90,   28,   28,   28,   28,
       27,   27,   54,   27,   77,   27,   63,   28,   42,   42,
       43,   43,   27,   38,   70,   27,   44,   44,   47,   47,
       40,   28,   45,   45,   27,   69,   41,   50,   50,   68,
       39,   59,   27,   40,   46,   46,   48,   48,   49,   49,
       51,   51,  100,   52,   52,   37,   43,   55,   55,   64,
       64,   72,   72,   32,   42,   73,   73,   29,   47,   43,
       74,   74,   47,   45,   43,   44,   76,   76,  101,   45,
       46,   21,   48,   18,   49,   82,   82,  100,   49,   52,

       50,   85,   85,   50,   87,   87,   87,   96,   96,   78,
       78,   51,   97,   97,   99,   99,  102,  102,   51,   65,
      104,  104,   65,  101,   78,   78,   78,   78,  103,  103,
       16,   65,   65,   65,   86,   78,   86,  107,  107,   86,
       86,   86,   86,  106,  106,   65,  105,  105,   65,   78,
      108,  108,   65,   65,   14,  109,  109,   65,    9,   83,
       83,  110,  110,    8,   65,   84,   84,   65,  103,   65,
       65,   65,  104,   65,   83,   83,   83,   83,   84,    7,
       84,   84,   84,   84,  106,   83,  111,  111,    6,  107,
        5,   84,  112,  112,  105,    4,  108,  113,  113,   83,

      114,  114,  115,  115,    3,   84,  109,  116,  116,  110,
      117,  117,  118,  118,  119,  119,    0,  120,  120,  121,
      121,  122,  122,  123,  123,  124,  124,  127,  127,  132,
      132,    0,  133,  133,    0,  133,  134,  140,  140,  111,
      143,  143,  135,  145,  145,  114,    0,  113,  117,    0,
      114,  154,  154,  116,  135,  135,  135,    0,  115,    0,
      118,  156,  156,  121,  133,  134,    0,  119,  120,  157,
      157,  135,    0,  123,    0,  122,  124,  136,  147,    0,
      147,  150,  150,  147,  147,  147,  147,  163,  163,  136,
      136,  136,  136,    0,  158,  158,  150,  150,  136,  136,

      136,  151,  151,  151,  151,  157,  136,  153,  153,    0,
      136,  136,  136,  136,  136,  136,  138,  138,  138,  138,
      160,  160,  153,  153,  153,  138,  138,  138,  159,  159,
      168,  168,  148,  148,  158,  169,  169,  138,  138,  138,
      138,  138,  138,  139,  139,  139,  139,  148,  148,  148,
      148,    0,  139,  139,  139,  149,  160,  149,  148,    0,
      149,  149,  149,  149,  139,  139,  139,  139,  139,  139,
      141,  179,  148,  141,  152,  152,  161,  161,  162,  162,
      159,  159,    0,  164,  164,  165,  165,  166,  166,  152,
      152,  152,  152,  167,  167,  170,  170,  171,  171,  141,

      179,  172,  172,  141,  141,  173,  173,    0,  141,  174,
      174,  175,  175,  176,  176,  141,  161,    0,  141,    0,
      141,  164,  141,    0,  162,  177,  177,  178,  178,  221,
      162,  260,  181,  167,  165,    0,  166,  180,  180,    0,
      180,    0,  171,  172,  181,  181,  181,  186,  186,  188,
      188,  188,  188,  176,  190,  190,  190,  190,  221,  173,
      260,  181,    0,  174,  175,  177,    0,  189,  189,  180,
      182,  182,  182,  182,  193,  193,  195,  195,    0,  182,
      182,  182,  189,  189,  189,  189,  191,  191,  197,  197,
        0,  182,  182,  182,  182,  182,  182,  183,  183,  183,

      183,  191,  191,  191,  191,    0,  183,  183,  183,  199,
      199,  200,  200,  201,  201,  202,  202,    0,  183,  183,
      183,  183,  183,  183,  184,  184,  184,  184,  203,  203,
      204,  204,    0,  184,  184,  184,  205,  205,  206,  206,
      207,  207,  208,  208,    0,  184,  184,  184,  184,  184,
      184,  209,  209,  210,  210,    0,  200,  211,  211,  213,
      213,  214,  214,  215,  215,  216,  216,    0,  202,  217,
      217,    0,  203,  218,  218,  219,  219,  220,  220,    0,
      207,  224,  224,    0,  204,  226,  226,  228,  228,  229,
      229,  206,  230,  230,  233,  233,    0,  214,  234,  234,

      231,  231,    0,  215,  210,  232,  232,  217,  235,  235,
        0,  218,  237,  237,  236,  236,  216,  222,  222,  222,
      222,  239,  239,  238,  238,    0,  222,  222,  222,  240,
      240,  242,  242,  246,  246,  248,  248,  233,  222,  222,
      222,  222,  222,  222,  223,  223,  223,  223,  231,  253,
      253,  232,    0,  223,  223,  223,  236,  250,  250,  254,
      254,  235,  249,  249,    0,  223,  223,  223,  223,  223,
      223,  238,  240,    0,  239,  243,  243,  243,  243,  251,
      251,  255,  255,    0,  243,  243,  243,  256,  256,  257,
      257,  258,  258,  262,  262,    0,  243,  243,  243,  243,

      243,  243,  244,  244,  244,  244,  261,  261,  264,  264,
      250,  244,  244,  244,  263,  263,  249,  266,  266,  268,
      268,  255,    0,  244,  244,  244,  244,  244,  244,    0,
      251,  259,  259,  259,  259,  272,  272,  269,  269,    0,
      259,  259,  259,  276,  276,    0,  261,  278,  278,    0,
        0,    0,  259,  259,  259,  259,  259,  259,  273,  273,
        0,  275,  275,  263,  267,  267,  267,  267,    0,    0,
        0,    0,    0,  267,  267,  267,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  267,  267,  267,  267,  267,
      267,  269,  270,  270,  270,  270,    0,    0,    0,    0,

      273,  270,  270,  270,  275,    0,    0,    0,    0,    0,
        0,    0,    0,  270,  270,  270,  270,  270,  270,  280,
      280,  280,  280,  280,  280,  281,  281,  281,  281,  281,
      281,  282,  282,  282,  282,  282,  282,  283,  283,  283,
      283,  283,  283,  284,  284,  284,    0,  284,  284,  285,
      285,    0,    0,  285,  286,  286,  286,  286,  286,  286,
      287,    0,  287,  287,  287,  287,  288,  288,  288,  288,
        0,  288,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[109] =
    {   0,
1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 
    1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 
    1, 0, 1, 0, 0, 0, 1, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "src/lexer.l"
#line 2 "src/lexer.l"
    #include "node.hpp"
    #include "parser.tab.h"
    #include<iostream>
    using namespace std;
    long long int column = 1;
    #define YY_DECL extern "C" int yylex()
#line 871 "lex.yy.c"

#line 873 "lex.yy.c"

#define INITIAL 0
#define SINGLE_LINE_COMMENT 1
#define MULTI_LINE_COMMENT 2
#define EXTRA_SEMICOLON_MODE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 62 "src/lexer.l"

#line 64 "src/lexer.l"
    /* reserved keyword */

#line 1104 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 280 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 973 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 66 "src/lexer.l"
{ cout<<"Entering XS"<<endl;BEGIN(INITIAL); return SCOLON;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 68 "src/lexer.l"
{  yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return TRUE;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 69 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return FALSE;}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 70 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return NULLPOINTER;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 71 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return BREAK;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 72 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return CONTINUE;}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 73 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return FALLTHROUGH;}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 74 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return RETURN;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 76 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return TRUE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 77 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return FALSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 78 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return NULLPOINTER;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 79 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return BREAK;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 80 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return CONTINUE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 81 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return FALLTHROUGH;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 82 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return RETURN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return FUNC;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 85 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return STRUCT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return ELSE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 87 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return PACKAGE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 88 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return IF;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return FOR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 90 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return RANGE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 91 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return IMPORT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 92 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return VAR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 93 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return SWITCH;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 94 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return CASE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 95 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return NEW;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 96 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return CONST;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return MAP;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return DEFAULT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 99 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return MAKE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return GOTO;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return TYPE;}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 103 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return PLUSPLUS;}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 104 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return MINUSMINUS;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 105 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return PLUSPLUS;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 106 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return MINUSMINUS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return ANDNOT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 109 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return ELIPSIS;}
	YY_BREAK
/* unary operators */
case 40:
YY_RULE_SETUP
#line 112 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return ADD;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 113 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return SUB;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 114 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return NOT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return XOR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 116 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return MUL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 117 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return AND;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 118 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return OR;}
	YY_BREAK
/* binary operators */
case 47:
YY_RULE_SETUP
#line 122 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return LOGOR;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 123 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return LOGAND;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 124 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return ISEQ;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 125 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return NEQ;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 126 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return LESSEQ;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 127 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return GRTEQ;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 128 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return GRT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 129 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return LESS;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 130 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return MOD;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 131 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return QUOT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 132 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return SHL;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 133 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return SHR;}
	YY_BREAK
/* Assignment */
case 59:
YY_RULE_SETUP
#line 138 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return INFER_EQ;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 139 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return ASSGN_OP;}
	YY_BREAK
/*Paranthesis, Punctuations*/
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 143 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return RIGHTPARAN;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 144 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return RIGHTBRACE;}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 145 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return RIGHTSQUARE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 147 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return LEFTPARAN;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 148 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return RIGHTPARAN;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 149 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return LEFTBRACE;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 150 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return RIGHTBRACE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 151 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return LEFTSQUARE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 152 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return RIGHTSQUARE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 153 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return SCOLON;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 154 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return COLON;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 155 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return DOT;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 156 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return COMMA;}
	YY_BREAK
/*Identifiers and datatypes*/
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 161 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return FLOAT_VAL;}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 162 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return FLOAT_VAL;}
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 163 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return FLOAT_VAL;}
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 164 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); /*cout<<"HERE !!!"<<endl;*/ return INTEGER_VAL;}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 165 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return INTEGER_VAL;}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 166 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return INTEGER_VAL;}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 167 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return INTEGER_VAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 169 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return FLOAT_VAL;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 170 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return FLOAT_VAL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 171 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return FLOAT_VAL;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 172 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return INTEGER_VAL;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 173 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return INTEGER_VAL;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 174 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return INTEGER_VAL;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 175 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return INTEGER_VAL;}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 178 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return BYTE_VAL;}
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 179 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return BYTE_VAL;}
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 180 "src/lexer.l"
{ yylval.sval = strdup(yytext); BEGIN(EXTRA_SEMICOLON_MODE); return RAW_STRING; }
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 181 "src/lexer.l"
{ yylval.sval = strdup(yytext); BEGIN(EXTRA_SEMICOLON_MODE); return INTERPRETED_STRING; }
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 184 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return BYTE_VAL;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 185 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; return BYTE_VAL;}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 186 "src/lexer.l"
{ yylval.sval = strdup(yytext); return RAW_STRING; }
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 187 "src/lexer.l"
{ yylval.sval = strdup(yytext); return INTERPRETED_STRING; }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 189 "src/lexer.l"
{ yylval.sval = strdup(yytext); cout<<yytext<<"--LEXER\n"; column+=yyleng; BEGIN(EXTRA_SEMICOLON_MODE); return IDENTIFIER;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 190 "src/lexer.l"
{ yylval.sval = strdup(yytext); cout<<yytext<<"--LEXER\n"; column+=yyleng; return IDENTIFIER;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 192 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 193 "src/lexer.l"
{column+=4;yyleng=4;}
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 194 "src/lexer.l"
{;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 197 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(SINGLE_LINE_COMMENT);}
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 198 "src/lexer.l"
{column=1; BEGIN(INITIAL);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 199 "src/lexer.l"
;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 201 "src/lexer.l"
{ yylval.sval = strdup(yytext); column+=yyleng; BEGIN(MULTI_LINE_COMMENT);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 202 "src/lexer.l"
{column=1; BEGIN(INITIAL);}
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 203 "src/lexer.l"
;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 206 "src/lexer.l"
{cout<<"Bad character in "<<yylineno<<" column number "<<column<<"\n"; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 208 "src/lexer.l"
ECHO;
	YY_BREAK
#line 1770 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(SINGLE_LINE_COMMENT):
			case YY_STATE_EOF(MULTI_LINE_COMMENT):
			case YY_STATE_EOF(EXTRA_SEMICOLON_MODE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 280 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 280 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 279);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 208 "src/lexer.l"


int yywrap(void)
{
    return 1;
}
